# Site settings
title: My little bloggy thing
email: max@vasiliev.me
description: "Frontend developer by day. Backend developer by night."
baseurl: ""
blogurl: "blog"
url: "http://www.vasiliev.me"
twitter_username: skammer
github_username:  skammer
linkedin_username: maxvasiliev
facebook_username: max.vasiliev
paginate: 1 

# Build settings
markdown: kramdown
# permalink: pretty
permalink: /blog/:title/
highlighter: rouge
